version: '3.8'
services:
   web:
       build: .
       volumes:
         - .:/core
       command: bash -c "uvicorn core.main:app --host 0.0.0.0 --port 8080 && xhost +"
       ports:
         - "8080:8080"
         - "8888:8888"
         - "4444:4444"
